/** Central route registry so links stay consistent and refactor-safe. */

export const routes = {
  home: "/",
  bagis: "/bagis",
  bagisDetay: (slug: string) => `/bagis/${slug}`,
  odeme: "/bagis/odeme",
  bagisBasarili: "/bagis/basarili",
  bagisDurum: "/bagis/durum",
  bagisTakip: "/bagis-takip",
  dekontBildir: "/dekont-bildir",

  kurban: "/kurban",
  ramazan: "/ramazan",

  faaliyetler: "/faaliyetler",
  afrika: "/faaliyetler/afrika",
  afganistan: "/faaliyetler/afganistan",
  pakistan: "/faaliyetler/pakistan",
  turkiye: "/faaliyetler/turkiye",
  gidaYardimi: "/faaliyetler/gida-yardimi",
  acilYardim: "/faaliyetler/acil-yardim",
  kurumsalDestek: "/kurumsal-destek",

  raporlar: "/raporlar",
  raporDetay: (slug: string) => `/raporlar/${slug}`,
  haberler: "/haberler",
  haberDetay: (slug: string) => `/haberler/${slug}`,
  galeri: "/galeri",
  galeriDetay: (slug: string) => `/galeri/${slug}`,

  hakkimizda: "/hakkimizda",
  gonulluOl: "/gonullu-ol",
  iletisim: "/iletisim",
  sss: "/sss",
  yasal: "/yasal",
  arama: "/arama",
  formBasarili: "/form-basarili",
  bakim: "/bakim",

  admin: {
    login: "/admin/login",
    dashboard: "/admin/dashboard",
    kampanyalar: "/admin/kampanyalar",
    kampanyaYeni: "/admin/kampanyalar/yeni",
    kampanyaDuzenle: (id: string) => `/admin/kampanyalar/${id}/duzenle`,
    bagislar: "/admin/bagislar",
    bagisDetay: (id: string) => `/admin/bagislar/${id}`,
    bagiscilar: "/admin/bagiscilar",
    kurbanTakibi: "/admin/kurban-takibi",
    ramazan: "/admin/ramazan-yardimlari",
    gonulluler: "/admin/gonulluler",
    dekontlar: "/admin/dekont-bildirimleri",
    raporlar: "/admin/raporlar",
    raporYeni: "/admin/raporlar/yeni",
    raporDuzenle: (id: string) => `/admin/raporlar/${id}/duzenle`,
    medya: "/admin/medya",
    mesajlar: "/admin/mesajlar",
    mesajDetay: (id: string) => `/admin/mesajlar/${id}`,
    icerikler: "/admin/sayfa-icerikleri",
    ayarlar: "/admin/ayarlar",
    bildirimSablonlari: "/admin/ayarlar/bildirim-sablonlari",
    yedekleme: "/admin/ayarlar/yedekleme",
    kullanicilar: "/admin/kullanicilar",
    islemKayitlari: "/admin/islem-kayitlari",
    profil: "/admin/profil",
  },
} as const;
